FROM maven:3.9.9-eclipse-temurin-17 AS BUILD

WORKDIR /projects

COPY pom.xml .
COPY spring-common/src spring-common/src
COPY spring-common/pom.xml spring-common/pom.xml
COPY reactive-api/src reactive-api/src
COPY reactive-api/pom.xml reactive-api/pom.xml
COPY servlet-api/src servlet-api/src
COPY servlet-api/pom.xml servlet-api/pom.xml
# Build the application using Maven
RUN mvn -U clean package -DskipTests

FROM eclipse-temurin:17-jdk-focal
ENV PORT 8081
EXPOSE 8081

COPY --from=BUILD /projects/servlet-api/target/*.jar /opt/app.jar
WORKDIR /opt/
CMD ["java", "-jar", "app.jar"]
