apiVersion: apps/v1
kind: Deployment
metadata:
  name: generate-containerize-and-deploy
  labels:
    app: generate-containerize-and-deploy
    kubernetes.azure.com/generator: devhub
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: generate-containerize-and-deploy
  template:
    metadata:
      labels:
        app: generate-containerize-and-deploy
    spec:
      containers:
        - name: generate-containerize-and-deploy
          image: acrpegersoft.azurecr.io/ps-servlet-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
