apiVersion: v1
kind: Service
metadata:
  name: ps-reactive-api
  labels:
    service: ps-reactive-api
spec:
  selector:
    app: ps-reactive-api
    type: api
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
status: {}