apiVersion: v1
kind: Service
metadata:
  name: ps-servlet-api
  labels:
    service: ps-servlet-api
spec:
  selector:
    app: ps-servlet-api
    type: api
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
status: {}