apiVersion: v1
kind: Service
metadata:
  name: generate-containerize-and-deploy
  namespace: default
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: generate-containerize-and-deploy
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080